-- Crear tabla de Kanji
CREATE TABLE IF NOT EXISTS kanji (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kanji TEXT NOT NULL,
  onyomi TEXT,
  kunyomi TEXT,
  meaning TEXT
);

-- Crear tabla de Vocabulario
CREATE TABLE IF NOT EXISTS vocabulary (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  word TEXT NOT NULL,
  reading TEXT NOT NULL,
  meaning TEXT NOT NULL,
  level TEXT CHECK(level IN ('N4', 'N3')) NOT NULL
);

-- Crear tabla de Gramática
CREATE TABLE IF NOT EXISTS grammar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  structure TEXT NOT NULL,
  explanation TEXT,
  example TEXT,
  level TEXT CHECK(level IN ('N4', 'N3'))
);

-- Insertar datos de ejemplo en la tabla de Kanji
INSERT INTO kanji (kanji, onyomi, kunyomi, meaning) VALUES
  ('一', 'イチ', 'ひと-', 'Uno'),
  ('二', 'ニ', 'ふた-', 'Dos'),
  ('三', 'サン', 'み-', 'Tres'),
  ('四', 'シ', 'よん', 'Cuatro'),
  ('五', 'ゴ', 'いつ', 'Cinco'),
  ('六', 'ロク', 'むっ-', 'Seis'),
  ('七', 'シチ', 'なな', 'Siete'),
  ('八', 'ハチ', 'やっ-', 'Ocho'),
  ('九', 'キュウ', 'ここの', 'Nueve'),
  ('十', 'ジュウ', 'とお', 'Diez'),
  ('山', 'サン', 'やま', 'Montaña'),
  ('川', 'セン', 'かわ', 'Río'),
  ('日', 'ニチ', 'ひ', 'Día/Sol'),
  ('月', 'ゲツ', 'つき', 'Luna/Mes'),
  ('火', 'カ', 'ひ', 'Fuego'),
  ('水', 'スイ', 'みず', 'Agua'),
  ('木', 'ボク', 'き', 'Árbol'),
  ('金', 'キン', 'かね', 'Metal/Dinero'),
  ('土', 'ド', 'つち', 'Tierra'),
  ('愛', 'アイ', 'いと.しい', 'Amor'),
  ('案', 'アン', 'つくえ', 'Idea, plan'),
  ('以', 'イ', 'もっ.て', 'Por medio de'),
  ('位', 'イ', 'くらい', 'Rango, posición'),
  ('因', 'イン', 'よ.る', 'Causa, razón'),
  ('永', 'エイ', 'なが.い', 'Eterno, largo'),
  ('衛', 'エイ', 'まも.る', 'Defender, proteger'),
  ('易', 'エキ', 'やさ.しい', 'Fácil, cambio'),
  ('益', 'エキ', 'ます', 'Beneficio, ganancia'),
  ('液', 'エキ', ' ', 'Líquido, fluido'),
  ('演', 'エン', ' ', 'Actuación, interpretar'),
  ('応', 'オウ', 'こた.える', 'Responder, reaccionar'),
  ('可', 'カ', 'べ.き', 'Aprobación, posible'),
  ('仮', 'カ', 'かり', 'Temporal, provisional'),
  ('価', 'カ', 'あたい', 'Valor, precio'),
  ('河', 'カ', 'かわ', 'Río, corriente'),
  ('過', 'カ', 'す.ぎる', 'Exceso, pasado'),
  ('解', 'カイ', 'と.く', 'Entender, resolver'),
  ('格', 'カク', ' ', 'Norma, estatus'),
  ('確', 'カク', 'たし.か', 'Seguro, certeza'),
  ('額', 'ガク', 'ひたい', 'Frente, cantidad'),
  ('刊', 'カン', ' ', 'Publicación, edición'),
  ('幹', 'カン', 'みき', 'Tronco, eje'),
  ('慣', 'カン', 'な.れる', 'Habituarse, costumbre'),
  ('観', 'カン', 'み.る', 'Mirar, observar'),
  ('願', 'ガン', 'ねが.う', 'Deseo, petición'),
  ('器', 'キ', 'うつわ', 'Recipiente, capacidad'),
  ('機', 'キ', 'はた', 'Máquina, oportunidad'),
  ('議', 'ギ', ' ', 'Debate, deliberación'),
  ('求', 'キュウ', 'もと.める', 'Pedir, desear'),
  ('泣', 'キュウ', 'な.く', 'Llorar'),
  ('給', 'キュウ', 'たま.う', 'Suministrar, salario'),
  ('挙', 'キョ', 'あ.げる', 'Levantar, alzar'),
  ('漁', 'ギョ', 'あさ.る', 'Pesca, pescador'),
  ('共', 'キョウ', 'とも', 'Junto, ambos'),
  ('協', 'キョウ', ' ', 'Cooperación, unión'),
  ('鏡', 'キョウ', 'かがみ', 'Espejo'),
  ('競', 'キョウ', 'きそ.う', 'Competir'),
  ('極', 'キョク', 'きわ.める', 'Extremo, máximo'),
  ('訓', 'クン', 'おし.える', 'Instrucción, enseñanza'),
  ('軍', 'グン', 'いくさ', 'Ejército, tropa'),
  ('郡', 'グン', ' ', 'Distrito, condado'),
  ('径', 'ケイ', 'みち', 'Diámetro, ruta'),
  ('景', 'ケイ', ' ', 'Paisaje, vista'),
  ('芸', 'ゲイ', ' ', 'Arte, habilidad'),
  ('欠', 'ケツ', 'か.ける', 'Falta, deficiencia'),
  ('結', 'ケツ', 'むす.ぶ', 'Atar, conectar'),
  ('建', 'ケン', 'た.てる', 'Construir, edificar'),
  ('健', 'ケン', 'すこ.やか', 'Salud, fuerte'),
  ('験', 'ケン', ' ', 'Prueba, examen'),
  ('険', 'ケン', 'けわ.しい', 'Empinado, peligroso'),
  ('限', 'ゲン', 'かぎ.る', 'Límite, restringir'),
  ('現', 'ゲン', 'あらわ.れる', 'Aparecer, realidad'),
  ('減', 'ゲン', 'へ.る', 'Disminuir, reducir'),
  ('故', 'コ', 'ゆえ', 'Razón, causa'),
  ('個', 'コ', ' ', 'Individuo, contador'),
  ('護', 'ゴ', 'まも.る', 'Proteger, defensa'),
  ('厚', 'コウ', 'あつ.い', 'Grueso, cordial'),
  ('耕', 'コウ', 'たがや.す', 'Arar, cultivar'),
  ('鉱', 'コウ', 'あらがね', 'Mineral, mina'),
  ('構', 'コウ', 'かま.う', 'Estructura, organizar'),
  ('興', 'コウ', 'おこ.る', 'Interés, prosperar'),
  ('講', 'コウ', ' ', 'Conferencia, discurso'),
  ('混', 'コン', 'ま.じる', 'Mezclar, confusión'),
  ('査', 'サ', ' ', 'Inspección, investigación'),
  ('再', 'サイ', 'ふたた.び', 'Otra vez, repetir'),
  ('災', 'サイ', 'わざわ.い', 'Desastre, calamidad'),
  ('妻', 'サイ', 'つま', 'Esposa'),
  ('採', 'サイ', 'と.る', 'Recolectar, adoptar'),
  ('際', 'サイ', 'きわ', 'Ocasión, borde'),
  ('在', 'ザイ', 'あ.る', 'Existir, estar en'),
  ('財', 'ザイ', 'たから', 'Bienes, riqueza'),
  ('罪', 'ザイ', 'つみ', 'Crimen, culpa'),
  ('雑', 'ザツ', ' ', 'Varios, misceláneo'),
  ('酸', 'サン', 'す.い', 'Ácido, agrio'),
  ('賛', 'サン', ' ', 'Aprobar, elogiar'),
  ('支', 'シ', 'ささ.える', 'Apoyar, rama'),
  ('志', 'シ', 'こころざ.す', 'Intención, deseo'),
  ('枝', 'シ', 'えだ', 'Rama, ramificación'),
  ('人', 'ジン', 'ひと', 'Persona');

-- Insertar datos de ejemplo en la tabla de Vocabulario
INSERT INTO vocabulary (word, reading, meaning, level) VALUES
  ('学校', 'がっこう', 'Escuela', 'N4'),
  ('先生', 'せんせい', 'Profesor', 'N4'),
  ('学生', 'がくせい', 'Estudiante', 'N4'),
  ('旅行', 'りょこう', 'Viaje', 'N3'),
  ('仕事', 'しごと', 'Trabajo', 'N3'),
  ('本', 'ほん', 'Libro', 'N4'),
  ('猫', 'ねこ', 'Gato', 'N4'),
  ('犬', 'いぬ', 'Perro', 'N4'),
  ('山', 'やま', 'Montaña', 'N4'),
  ('川', 'かわ', 'Río', 'N4'),
  ('友達', 'ともだち', 'Amigo', 'N4'),
  ('家族', 'かぞく', 'Familia', 'N4'),
  ('時間', 'じかん', 'Tiempo', 'N4'),
  ('日本', 'にほん', 'Japón', 'N4'),
  ('外国', 'がいこく', 'Extranjero', 'N3'),
  ('電車', 'でんしゃ', 'Tren', 'N4'),
  ('飛行機', 'ひこうき', 'Avión', 'N3'),
  ('映画', 'えいが', 'Película', 'N3'),
  ('音楽', 'おんがく', 'Música', 'N3'),
  ('料理', 'りょうり', 'Cocina', 'N3'),
  ('勉強', 'べんきょう', 'Estudio', 'N4'),
  ('会話', 'かいわ', 'Conversación', 'N3'),
  ('天気', 'てんき', 'Clima', 'N4'),
  ('明日', 'あした', 'Mañana', 'N4'),
  ('昨日', 'きのう', 'Ayer', 'N4'),
  ('今日', 'きょう', 'Hoy', 'N4'),
   ('約束', 'やくそく', 'Promesa', 'N3'),
  ('会議', 'かいぎ', 'Reunión', 'N3'),
  ('意見', 'いけん', 'Opinión', 'N3'),
  ('課題', 'かだい', 'Tarea', 'N3'),
  ('結婚', 'けっこん', 'Matrimonio', 'N3'),
  ('健康', 'けんこう', 'Salud', 'N3'),
  ('失敗', 'しっぱい', 'Fracaso', 'N3'),
  ('準備', 'じゅんび', 'Preparación', 'N3'),
  ('生活', 'せいかつ', 'Vida cotidiana', 'N3'),
  ('選択', 'せんたく', 'Elección', 'N3'),
  ('相談', 'そうだん', 'Consulta', 'N3'),
  ('遅刻', 'ちこく', 'Llegar tarde', 'N3'),
  ('注意', 'ちゅうい', 'Atención', 'N3'),
  ('天気予報', 'てんきよほう', 'Pronóstico del tiempo', 'N3'),
  ('到着', 'とうちゃく', 'Llegada', 'N3'),
  ('入学', 'にゅうがく', 'Ingreso a la escuela', 'N3'),
  ('発表', 'はっぴょう', 'Presentación', 'N3'),
  ('反対', 'はんたい', 'Oposición', 'N3'),
  ('法律', 'ほうりつ', 'Ley', 'N3'),
  ('翻訳', 'ほんやく', 'Traducción', 'N3'),
  ('予約', 'よやく', 'Reserva', 'N3'),
  ('理解', 'りかい', 'Comprensión', 'N3'),
  ('留学', 'りゅうがく', 'Estudios en el extranjero', 'N3'),
  ('連絡', 'れんらく', 'Contacto', 'N3'),
  ('確認', 'かくにん', 'Confirmación', 'N3'),
  ('活動', 'かつどう', 'Actividad', 'N3'),
  ('練習', 'れんしゅう', 'Práctica', 'N3'),
  ('運転', 'うんてん', 'Conducción', 'N3'),
  ('影響', 'えいきょう', 'Influencia', 'N3'),
  ('応援', 'おうえん', 'Apoyo', 'N3'),
  ('改善', 'かいぜん', 'Mejora', 'N3'),
  ('感動', 'かんどう', 'Emoción', 'N3'),
  ('管理', 'かんり', 'Gestión', 'N3'),
  ('教育', 'きょういく', 'Educación', 'N3'),
  ('経験', 'けいけん', 'Experiencia', 'N3'),
  ('行動', 'こうどう', 'Acción', 'N3'),
  ('成功', 'せいこう', 'Éxito', 'N3'),
  ('成長', 'せいちょう', 'Crecimiento', 'N3'),
  ('説明', 'せつめい', 'Explicación', 'N3'),
  ('選挙', 'せんきょ', 'Elección (votación)', 'N3'),
  ('態度', 'たいど', 'Actitud', 'N3'),
  ('挑戦', 'ちょうせん', 'Desafío', 'N3'),
  ('貯金', 'ちょきん', 'Ahorro', 'N3'),
  ('努力', 'どりょく', 'Esfuerzo', 'N3'),
  ('発見', 'はっけん', 'Descubrimiento', 'N3'),
  ('反省', 'はんせい', 'Reflexión', 'N3'),
  ('翻訳', 'ほんやく', 'Traducción', 'N3'),
  ('魅力', 'みりょく', 'Encanto', 'N3'),
  ('目的', 'もくてき', 'Objetivo', 'N3'),
  ('予想', 'よそう', 'Predicción', 'N3'),
  ('理想', 'りそう', 'Ideal', 'N3'),
  ('理解', 'りかい', 'Comprensión', 'N3'),
  ('冷静', 'れいせい', 'Calma', 'N3'),
  ('連絡', 'れんらく', 'Contacto', 'N3'),
  ('報告', 'ほうこく', 'Informe', 'N3'),
  ('保証', 'ほしょう', 'Garantía', 'N3'),
  ('尊敬', 'そんけい', 'Respeto', 'N3'),
  ('投票', 'とうひょう', 'Votación', 'N3'),
  ('能力', 'のうりょく', 'Habilidad', 'N3'),
  ('発明', 'はつめい', 'Invención', 'N3'),
  ('平和', 'へいわ', 'Paz', 'N3'),
  ('目的', 'もくてき', 'Propósito', 'N3'),
  ('問題', 'もんだい', 'Problema', 'N3'),
  ('優勝', 'ゆうしょう', 'Victoria', 'N3'),
  ('勇気', 'ゆうき', 'Valentía', 'N3'),
  ('予算', 'よさん', 'Presupuesto', 'N3'),
  ('理解', 'りかい', 'Entendimiento', 'N3'),
  ('連携', 'れんけい', 'Cooperación', 'N3');

-- Insertar datos de ejemplo en la tabla de Gramática
INSERT INTO grammar (structure, explanation, example, level) VALUES
  ('～ます/～ません', 'Forma cortés para verbos.', '行きます (ikimasu) - Voy / No voy: 行きません (ikimasen)', 'N4'),
  ('～ている', 'Indica una acción en progreso o estado resultante.', '食べています (tabete imasu) - Estoy comiendo.', 'N3'),
  ('～たい', 'Expresa deseo de hacer algo.', '食べたい (tabetai) - Quiero comer.', 'N4'),
  ('～なければなりません', 'Indica obligación o necesidad.', '勉強しなければなりません (benkyou shinakereba narimasen) - Debo estudiar.', 'N3'),
  ('～てもいいです', 'Permite pedir o dar permiso.', '行っても良いですか？(Itte mo ii desu ka?) - ¿Puedo ir?', 'N4'),
  ('～ほうがいいです', 'Recomienda hacer algo.', '早く寝たほうがいいです (Hayaku netta hou ga ii desu) - Es mejor dormir temprano.', 'N3'),
  ('～たことがあります', 'Expresa experiencias pasadas.', '日本に行ったことがあります (Nihon ni itta koto ga arimasu) - He ido a Japón.', 'N3'),
  ('～ている', 'Indica una acción en progreso o estado resultante.', '食べています (tabete imasu) - Estoy comiendo.', 'N3'),
  ('～たばかり', 'Indica que algo acaba de suceder recientemente.', '日本に来たばかりです (Nihon ni kita bakari desu) - Acabo de llegar a Japón.', 'N3'),
  ('～ようになる', 'Indica un cambio en habilidad o estado.', '日本語が話せるようになりました (Nihongo ga hanaseru you ni narimashita) - He llegado a poder hablar japonés.', 'N3'),
  ('～ことになっている', 'Indica una regla o costumbre.', 'この会社ではスーツを着ることになっています (Kono kaisha de wa suutsu o kiru koto ni natte imasu) - En esta empresa se supone que debemos vestir traje.', 'N3'),
  ('～らしい', 'Indica que algo parece ser cierto basado en evidencia.', '彼は先生らしいです (Kare wa sensei rashii desu) - Parece que él es un profesor.', 'N3'),
  ('～ようだ', 'Expresa una suposición basada en la observación.', '雨が降っているようです (Ame ga futte iru you desu) - Parece que está lloviendo.', 'N3'),
  ('～ことにする', 'Indica una decisión personal.', '毎日運動することにしました (Mainichi undou suru koto ni shimashita) - Decidí hacer ejercicio todos los días.', 'N3'),
  ('～ことにしている', 'Indica un hábito decidido por el hablante.', '毎朝6時に起きることにしています (Maiasa roku ji ni okiru koto ni shiteimasu) - He decidido levantarme a las 6 cada mañana.', 'N3'),
  ('～ことがある', 'Expresa que algo ocurre ocasionalmente.', '日本料理を作ることがあります (Nihon ryouri o tsukuru koto ga arimasu) - A veces cocino comida japonesa.', 'N3'),
  ('～ようにする', 'Expresa un esfuerzo por hacer algo.', '毎日野菜を食べるようにしています (Mainichi yasai o taberu you ni shiteimasu) - Intento comer verduras todos los días.', 'N3'),
  ('～ばかり', 'Indica que algo se ha hecho en exceso.', '甘いものばかり食べています (Amai mono bakari tabeteimasu) - Solo como cosas dulces.', 'N3'),
  ('～てしまう', 'Expresa completitud o arrepentimiento.', '財布を忘れてしまいました (Saifu o wasurete shimaimashita) - Olvidé mi cartera.', 'N3'),
  ('～かもしれない', 'Indica una posibilidad.', '明日は雨が降るかもしれません (Ashita wa ame ga furu kamoshiremasen) - Puede que llueva mañana.', 'N3'),
  ('～はずだ', 'Expresa expectativa basada en conocimiento previo.', '彼は今家にいるはずです (Kare wa ima ie ni iru hazu desu) - Se supone que él está en casa ahora.', 'N3'),
  ('～ないで', 'Indica hacer algo sin hacer otra cosa.', '宿題をしないで寝ました (Shukudai o shinaide nemashita) - Me dormí sin hacer la tarea.', 'N3'),
  ('～ずに', 'Forma más formal de ～ないで.', '朝ご飯を食べずに学校へ行きました (Asagohan o tabezu ni gakkou e ikimashita) - Fui a la escuela sin desayunar.', 'N3'),
  ('～ても', 'Expresa que algo ocurre a pesar de otra cosa.', '雨が降っても試合は行われます (Ame ga futtemo shiai wa okonawaremasu) - Aunque llueva, el partido se llevará a cabo.', 'N3'),
  ('～といい', 'Indica deseo o esperanza.', '明日は晴れるといいですね (Ashita wa hareru to ii desu ne) - Ojalá haga buen tiempo mañana.', 'N3'),
  ('～ばいい', 'Sugiere una posible solución.', 'もっと勉強すればいいですよ (Motto benkyou sureba ii desu yo) - Deberías estudiar más.', 'N3'),
  ('～なさい', 'Forma imperativa suave.', '早く寝なさい (Hayaku nenasai) - Duerme temprano.', 'N3'),
  ('～ておく', 'Indica hacer algo con anticipación.', 'ホテルを予約しておきます (Hoteru o yoyaku shite okimasu) - Reservaré un hotel con antelación.', 'N3'),
  ('～ように言う', 'Expresa que se ha transmitido un mensaje o instrucción.', '先生に宿題を出すように言われました (Sensei ni shukudai o dasu you ni iwaremashita) - El profesor me dijo que entregara la tarea.', 'N3'),
  ('～という', 'Explica o cita algo dicho.', '田中さんは来週引っ越すという (Tanaka-san wa raishuu hikkosu to iu) - Dicen que Tanaka se muda la próxima semana.', 'N3'),
  ('～みたいだ', 'Expresa que algo parece ser cierto basado en la apariencia.', '彼は疲れているみたいです (Kare wa tsukarete iru mitai desu) - Parece que está cansado.', 'N3'),
  ('～ことになる', 'Expresa una decisión tomada por alguien más.', '来月から東京に住むことになりました (Raigetsu kara Tokyo ni sumu koto ni narimashita) - Se ha decidido que viviré en Tokio desde el próximo mes.', 'N3'),
  ('～てもかまわない', 'Indica permiso.', 'ここで写真を撮ってもかまいません (Koko de shashin o totte mo kamaimasen) - No hay problema si tomas fotos aquí.', 'N3'),
  ('～だけでなく', 'Indica que algo no se limita a una sola cosa.', '彼は英語だけでなくフランス語も話せます (Kare wa eigo dake de naku furansugo mo hanasemasu) - Él no solo habla inglés, sino también francés.', 'N3'),
  ('～ところ', 'Expresa el momento de una acción.', '今から食べるところです (Ima kara taberu tokoro desu) - Estoy a punto de comer.', 'N3'),
  ('～によると', 'Indica la fuente de una información.', '天気予報によると明日は晴れるそうです (Tenki yohou ni yoru to ashita wa hareru sou desu) - Según el pronóstico del tiempo, mañana hará sol.', 'N3'),
  ('～ながら', 'Indica realizar dos acciones simultáneamente.', '音楽を聞きながら勉強します (Ongaku o kikinagara benkyou shimasu) - Estudio mientras escucho música.', 'N3');